-- ============================================
-- CUSTOMERS
-- ============================================

CREATE TABLE customers (
    customer_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    current_balance DECIMAL(18,2) NOT NULL DEFAULT 0.00,
    age INT NULL,
    safety_buffer INT NOT NULL,
    city VARCHAR(100) NULL,
    country VARCHAR(100) NULL,

    CONSTRAINT chk_customer_age
        CHECK (age IS NULL OR age >= 0)
) ENGINE=InnoDB;


-- ============================================
-- CUSTOMER PREFERENCES
-- ============================================

CREATE TABLE customer_preferences (
    customer_id BIGINT UNSIGNED PRIMARY KEY,
    advice_opt_in BOOLEAN NOT NULL DEFAULT TRUE,
    notification_preference VARCHAR(50) NOT NULL DEFAULT 'in_app',

    CONSTRAINT fk_preferences_customer
        FOREIGN KEY (customer_id)
        REFERENCES customers(customer_id)
        ON DELETE CASCADE
) ENGINE=InnoDB;


-- ============================================
-- PRODUCTS
-- ============================================

CREATE TABLE products (
    product_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    product_type VARCHAR(100) NOT NULL,
    product_amount DECIMAL(18,2) NULL,

    CONSTRAINT chk_product_amount
        CHECK (product_amount IS NULL OR product_amount >= 0)
) ENGINE=InnoDB;


-- ============================================
-- CUSTOMER / PRODUCT LINK
-- ============================================

CREATE TABLE customer_product (
    customer_product_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    customer_id BIGINT UNSIGNED NOT NULL,
    product_id BIGINT UNSIGNED NOT NULL,

    CONSTRAINT fk_cpl_customer
        FOREIGN KEY (customer_id)
        REFERENCES customers(customer_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_cpl_product
        FOREIGN KEY (product_id)
        REFERENCES products(product_id)
        ON DELETE CASCADE,

    CONSTRAINT uq_customer_product
        UNIQUE (customer_id, product_id)
) ENGINE=InnoDB;


-- ============================================
-- TRANSACTIONS
-- ============================================

CREATE TABLE transactions (
    transaction_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    customer_id BIGINT UNSIGNED NOT NULL,
    product_id BIGINT UNSIGNED NOT NULL,
    transaction_date DATETIME NOT NULL,
    amount DECIMAL(18,2) NOT NULL,
    merchant VARCHAR(255) NULL,
    merchant_category VARCHAR(100) NULL,
    payment_method VARCHAR(50) NULL,

    CONSTRAINT fk_transactions_customer
        FOREIGN KEY (customer_id)
        REFERENCES customers(customer_id),

    CONSTRAINT fk_transactions_product
        FOREIGN KEY (product_id)
        REFERENCES products(product_id)
) ENGINE=InnoDB;


-- ============================================
-- EVENTS
-- ============================================

CREATE TABLE events (
    event_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    event_type VARCHAR(100) NOT NULL,
    event_date DATETIME NOT NULL,
    event_value TEXT NULL
) ENGINE=InnoDB;


-- ============================================
-- CUSTOMER EVENTS
-- ============================================

CREATE TABLE customer_events (
    customer_event_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    event_id BIGINT UNSIGNED NOT NULL,
    customer_id BIGINT UNSIGNED NOT NULL,

    CONSTRAINT fk_customer_events_event
        FOREIGN KEY (event_id)
        REFERENCES events(event_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_customer_events_customer
        FOREIGN KEY (customer_id)
        REFERENCES customers(customer_id)
        ON DELETE CASCADE,

    CONSTRAINT uq_customer_event
        UNIQUE (customer_id, event_id)
) ENGINE=InnoDB;


-- ============================================
-- INDEXES
-- ============================================

CREATE INDEX idx_cpl_customer
    ON customer_product(customer_id);

CREATE INDEX idx_cpl_product
    ON customer_product(product_id);

CREATE INDEX idx_transactions_customer
    ON transactions(customer_id);

CREATE INDEX idx_transactions_product
    ON transactions(product_id);

CREATE INDEX idx_transactions_date
    ON transactions(transaction_date);

CREATE INDEX idx_transactions_customer_date
    ON transactions(customer_id, transaction_date);

CREATE INDEX idx_events_type
    ON events(event_type);

CREATE INDEX idx_events_date
    ON events(event_date);

CREATE INDEX idx_customer_events_customer
    ON customer_events(customer_id);

CREATE INDEX idx_customer_events_event
    ON customer_events(event_id);


-- SYNTHETIC DEMO ONLY. Generated by scripts/future_demo_data.py --sql.

-- Six months: 2026-04-01 through 2026-09-30; balances at 2026-09-30 close.

-- Fresh database seed. Do not run against an existing populated database.

START TRANSACTION;

INSERT INTO customers (customer_id, name, current_balance, safety_buffer) VALUES
    (1001, 'Alex Demo', 1940.00, 250),
    (1002, 'Sam Safe', 4500.00, 300),
    (1003, 'Robin Uncertain', 900.00, 250);

INSERT INTO customer_preferences (customer_id, advice_opt_in, notification_preference) VALUES
    (1001, 1, 'in_app'),
    (1002, 1, 'in_app'),
    (1003, 1, 'in_app');

INSERT INTO products (product_id, product_type, product_amount) VALUES
    (2001, 'current_account', 1940.00),
    (2002, 'current_account', 4500.00),
    (2003, 'current_account', 900.00);

INSERT INTO customer_product (customer_id, product_id) VALUES
    (1001, 2001),
    (1002, 2002),
    (1003, 2003);

INSERT INTO transactions (transaction_id, customer_id, product_id, transaction_date, amount, merchant, merchant_category, payment_method) VALUES
    (900001, 1001, 2001, '2026-04-02 12:00:00', -39.00, 'Demo Grocer A', 'groceries', 'card'),
    (900002, 1001, 2001, '2026-04-03 12:00:00', -900.00, 'Demo Housing A', 'rent', 'direct_debit'),
    (900003, 1001, 2001, '2026-04-05 12:00:00', -15.00, 'Demo Transit A', 'transport', 'card'),
    (900004, 1001, 2001, '2026-04-06 12:00:00', -39.00, 'Demo Grocer A', 'groceries', 'card'),
    (900005, 1001, 2001, '2026-04-07 12:00:00', -35.00, 'Demo Cafe A', 'dining', 'card'),
    (900006, 1001, 2001, '2026-04-08 12:00:00', -33.34, 'Demo Shop A', 'shopping', 'card'),
    (900007, 1001, 2001, '2026-04-10 12:00:00', -39.00, 'Demo Grocer A', 'groceries', 'card'),
    (900008, 1001, 2001, '2026-04-12 12:00:00', -90.00, 'Demo Insurer A', 'insurance', 'direct_debit'),
    (900009, 1001, 2001, '2026-04-12 12:00:00', -15.00, 'Demo Transit A', 'transport', 'card'),
    (900010, 1001, 2001, '2026-04-14 12:00:00', -35.00, 'Demo Cafe A', 'dining', 'card'),
    (900011, 1001, 2001, '2026-04-14 12:00:00', -39.00, 'Demo Grocer A', 'groceries', 'card'),
    (900012, 1001, 2001, '2026-04-17 12:00:00', -33.33, 'Demo Shop A', 'shopping', 'card'),
    (900013, 1001, 2001, '2026-04-18 12:00:00', -100.00, 'Demo Energy A', 'utilities', 'direct_debit'),
    (900014, 1001, 2001, '2026-04-18 12:00:00', -39.00, 'Demo Grocer A', 'groceries', 'card'),
    (900015, 1001, 2001, '2026-04-19 12:00:00', -15.00, 'Demo Transit A', 'transport', 'card'),
    (900016, 1001, 2001, '2026-04-21 12:00:00', -35.00, 'Demo Cafe A', 'dining', 'card'),
    (900017, 1001, 2001, '2026-04-22 12:00:00', -39.00, 'Demo Grocer A', 'groceries', 'card'),
    (900018, 1001, 2001, '2026-04-25 12:00:00', -33.33, 'Demo Shop A', 'shopping', 'card'),
    (900019, 1001, 2001, '2026-04-26 12:00:00', -39.00, 'Demo Grocer A', 'groceries', 'card'),
    (900020, 1001, 2001, '2026-04-26 12:00:00', -15.00, 'Demo Transit A', 'transport', 'card'),
    (900021, 1001, 2001, '2026-04-27 12:00:00', -35.00, 'Demo Cafe A', 'dining', 'card'),
    (900022, 1001, 2001, '2026-04-28 12:00:00', 2100.00, 'Demo Employer A', 'salary', 'bank_transfer'),
    (900023, 1001, 2001, '2026-04-29 12:00:00', -39.00, 'Demo Grocer A', 'groceries', 'card'),
    (900024, 1001, 2001, '2026-04-29 12:00:00', -1200.00, 'Demo Repair', 'home_repair', 'bank_transfer'),
    (900025, 1001, 2001, '2026-05-02 12:00:00', -40.75, 'Demo Grocer A', 'groceries', 'card'),
    (900026, 1001, 2001, '2026-05-03 12:00:00', -900.00, 'Demo Housing A', 'rent', 'direct_debit'),
    (900027, 1001, 2001, '2026-05-05 12:00:00', -15.00, 'Demo Transit A', 'transport', 'card'),
    (900028, 1001, 2001, '2026-05-06 12:00:00', -40.75, 'Demo Grocer A', 'groceries', 'card'),
    (900029, 1001, 2001, '2026-05-07 12:00:00', -45.00, 'Demo Cafe A', 'dining', 'card'),
    (900030, 1001, 2001, '2026-05-08 12:00:00', -40.00, 'Demo Shop A', 'shopping', 'card'),
    (900031, 1001, 2001, '2026-05-10 12:00:00', -40.75, 'Demo Grocer A', 'groceries', 'card'),
    (900032, 1001, 2001, '2026-05-12 12:00:00', -90.00, 'Demo Insurer A', 'insurance', 'direct_debit'),
    (900033, 1001, 2001, '2026-05-12 12:00:00', -15.00, 'Demo Transit A', 'transport', 'card'),
    (900034, 1001, 2001, '2026-05-14 12:00:00', -45.00, 'Demo Cafe A', 'dining', 'card'),
    (900035, 1001, 2001, '2026-05-14 12:00:00', -40.75, 'Demo Grocer A', 'groceries', 'card'),
    (900036, 1001, 2001, '2026-05-17 12:00:00', -40.00, 'Demo Shop A', 'shopping', 'card'),
    (900037, 1001, 2001, '2026-05-18 12:00:00', -100.00, 'Demo Energy A', 'utilities', 'direct_debit'),
    (900038, 1001, 2001, '2026-05-18 12:00:00', -40.75, 'Demo Grocer A', 'groceries', 'card'),
    (900039, 1001, 2001, '2026-05-19 12:00:00', -15.00, 'Demo Transit A', 'transport', 'card'),
    (900040, 1001, 2001, '2026-05-21 12:00:00', -45.00, 'Demo Cafe A', 'dining', 'card'),
    (900041, 1001, 2001, '2026-05-22 12:00:00', -40.75, 'Demo Grocer A', 'groceries', 'card'),
    (900042, 1001, 2001, '2026-05-25 12:00:00', -40.00, 'Demo Shop A', 'shopping', 'card'),
    (900043, 1001, 2001, '2026-05-26 12:00:00', -40.75, 'Demo Grocer A', 'groceries', 'card'),
    (900044, 1001, 2001, '2026-05-26 12:00:00', -15.00, 'Demo Transit A', 'transport', 'card'),
    (900045, 1001, 2001, '2026-05-27 12:00:00', -45.00, 'Demo Cafe A', 'dining', 'card'),
    (900046, 1001, 2001, '2026-05-28 12:00:00', 2100.00, 'Demo Employer A', 'salary', 'bank_transfer'),
    (900047, 1001, 2001, '2026-05-29 12:00:00', -40.75, 'Demo Grocer A', 'groceries', 'card'),
    (900048, 1001, 2001, '2026-06-02 12:00:00', -39.75, 'Demo Grocer A', 'groceries', 'card'),
    (900049, 1001, 2001, '2026-06-03 12:00:00', -900.00, 'Demo Housing A', 'rent', 'direct_debit'),
    (900050, 1001, 2001, '2026-06-05 12:00:00', -15.00, 'Demo Transit A', 'transport', 'card'),
    (900051, 1001, 2001, '2026-06-06 12:00:00', -39.75, 'Demo Grocer A', 'groceries', 'card'),
    (900052, 1001, 2001, '2026-06-07 12:00:00', -55.00, 'Demo Cafe A', 'dining', 'card'),
    (900053, 1001, 2001, '2026-06-08 12:00:00', -53.34, 'Demo Shop A', 'shopping', 'card'),
    (900054, 1001, 2001, '2026-06-10 12:00:00', -39.75, 'Demo Grocer A', 'groceries', 'card'),
    (900055, 1001, 2001, '2026-06-12 12:00:00', -90.00, 'Demo Insurer A', 'insurance', 'direct_debit'),
    (900056, 1001, 2001, '2026-06-12 12:00:00', -15.00, 'Demo Transit A', 'transport', 'card'),
    (900057, 1001, 2001, '2026-06-14 12:00:00', -55.00, 'Demo Cafe A', 'dining', 'card'),
    (900058, 1001, 2001, '2026-06-14 12:00:00', -39.75, 'Demo Grocer A', 'groceries', 'card'),
    (900059, 1001, 2001, '2026-06-17 12:00:00', -53.33, 'Demo Shop A', 'shopping', 'card'),
    (900060, 1001, 2001, '2026-06-18 12:00:00', -100.00, 'Demo Energy A', 'utilities', 'direct_debit'),
    (900061, 1001, 2001, '2026-06-18 12:00:00', -39.75, 'Demo Grocer A', 'groceries', 'card'),
    (900062, 1001, 2001, '2026-06-19 12:00:00', -15.00, 'Demo Transit A', 'transport', 'card'),
    (900063, 1001, 2001, '2026-06-21 12:00:00', -55.00, 'Demo Cafe A', 'dining', 'card'),
    (900064, 1001, 2001, '2026-06-22 12:00:00', -39.75, 'Demo Grocer A', 'groceries', 'card'),
    (900065, 1001, 2001, '2026-06-25 12:00:00', -53.33, 'Demo Shop A', 'shopping', 'card'),
    (900066, 1001, 2001, '2026-06-26 12:00:00', -39.75, 'Demo Grocer A', 'groceries', 'card'),
    (900067, 1001, 2001, '2026-06-26 12:00:00', -15.00, 'Demo Transit A', 'transport', 'card'),
    (900068, 1001, 2001, '2026-06-27 12:00:00', -55.00, 'Demo Cafe A', 'dining', 'card'),
    (900069, 1001, 2001, '2026-06-28 12:00:00', 2100.00, 'Demo Employer A', 'salary', 'bank_transfer'),
    (900070, 1001, 2001, '2026-06-29 12:00:00', -39.75, 'Demo Grocer A', 'groceries', 'card'),
    (900071, 1001, 2001, '2026-07-02 12:00:00', -38.75, 'Demo Grocer A', 'groceries', 'card'),
    (900072, 1001, 2001, '2026-07-03 12:00:00', -900.00, 'Demo Housing A', 'rent', 'direct_debit'),
    (900073, 1001, 2001, '2026-07-05 12:00:00', -15.00, 'Demo Transit A', 'transport', 'card'),
    (900074, 1001, 2001, '2026-07-06 12:00:00', -38.75, 'Demo Grocer A', 'groceries', 'card'),
    (900075, 1001, 2001, '2026-07-07 12:00:00', -20.00, 'Demo Cafe A', 'dining', 'card'),
    (900076, 1001, 2001, '2026-07-08 12:00:00', -13.34, 'Demo Shop A', 'shopping', 'card'),
    (900077, 1001, 2001, '2026-07-10 12:00:00', -38.75, 'Demo Grocer A', 'groceries', 'card'),
    (900078, 1001, 2001, '2026-07-12 12:00:00', -90.00, 'Demo Insurer A', 'insurance', 'direct_debit'),
    (900079, 1001, 2001, '2026-07-12 12:00:00', -15.00, 'Demo Transit A', 'transport', 'card'),
    (900080, 1001, 2001, '2026-07-14 12:00:00', -20.00, 'Demo Cafe A', 'dining', 'card'),
    (900081, 1001, 2001, '2026-07-14 12:00:00', -38.75, 'Demo Grocer A', 'groceries', 'card'),
    (900082, 1001, 2001, '2026-07-17 12:00:00', -13.33, 'Demo Shop A', 'shopping', 'card'),
    (900083, 1001, 2001, '2026-07-18 12:00:00', -100.00, 'Demo Energy A', 'utilities', 'direct_debit'),
    (900084, 1001, 2001, '2026-07-18 12:00:00', -38.75, 'Demo Grocer A', 'groceries', 'card'),
    (900085, 1001, 2001, '2026-07-19 12:00:00', -15.00, 'Demo Transit A', 'transport', 'card'),
    (900086, 1001, 2001, '2026-07-21 12:00:00', -20.00, 'Demo Cafe A', 'dining', 'card'),
    (900087, 1001, 2001, '2026-07-22 12:00:00', -38.75, 'Demo Grocer A', 'groceries', 'card'),
    (900088, 1001, 2001, '2026-07-25 12:00:00', -13.33, 'Demo Shop A', 'shopping', 'card'),
    (900089, 1001, 2001, '2026-07-26 12:00:00', -38.75, 'Demo Grocer A', 'groceries', 'card'),
    (900090, 1001, 2001, '2026-07-26 12:00:00', -15.00, 'Demo Transit A', 'transport', 'card'),
    (900091, 1001, 2001, '2026-07-27 12:00:00', -20.00, 'Demo Cafe A', 'dining', 'card'),
    (900092, 1001, 2001, '2026-07-28 12:00:00', 2100.00, 'Demo Employer A', 'salary', 'bank_transfer'),
    (900093, 1001, 2001, '2026-07-29 12:00:00', -38.75, 'Demo Grocer A', 'groceries', 'card'),
    (900094, 1001, 2001, '2026-08-02 12:00:00', -40.00, 'Demo Grocer A', 'groceries', 'card'),
    (900095, 1001, 2001, '2026-08-03 12:00:00', -900.00, 'Demo Housing A', 'rent', 'direct_debit'),
    (900096, 1001, 2001, '2026-08-05 12:00:00', -15.00, 'Demo Transit A', 'transport', 'card'),
    (900097, 1001, 2001, '2026-08-06 12:00:00', -40.00, 'Demo Grocer A', 'groceries', 'card'),
    (900098, 1001, 2001, '2026-08-07 12:00:00', -50.00, 'Demo Cafe A', 'dining', 'card'),
    (900099, 1001, 2001, '2026-08-08 12:00:00', -53.34, 'Demo Shop A', 'shopping', 'card'),
    (900100, 1001, 2001, '2026-08-10 12:00:00', -40.00, 'Demo Grocer A', 'groceries', 'card'),
    (900101, 1001, 2001, '2026-08-12 12:00:00', -90.00, 'Demo Insurer A', 'insurance', 'direct_debit'),
    (900102, 1001, 2001, '2026-08-12 12:00:00', -15.00, 'Demo Transit A', 'transport', 'card'),
    (900103, 1001, 2001, '2026-08-14 12:00:00', -50.00, 'Demo Cafe A', 'dining', 'card'),
    (900104, 1001, 2001, '2026-08-14 12:00:00', -40.00, 'Demo Grocer A', 'groceries', 'card'),
    (900105, 1001, 2001, '2026-08-17 12:00:00', -53.33, 'Demo Shop A', 'shopping', 'card'),
    (900106, 1001, 2001, '2026-08-18 12:00:00', -100.00, 'Demo Energy A', 'utilities', 'direct_debit'),
    (900107, 1001, 2001, '2026-08-18 12:00:00', -40.00, 'Demo Grocer A', 'groceries', 'card'),
    (900108, 1001, 2001, '2026-08-19 12:00:00', -15.00, 'Demo Transit A', 'transport', 'card'),
    (900109, 1001, 2001, '2026-08-21 12:00:00', -50.00, 'Demo Cafe A', 'dining', 'card'),
    (900110, 1001, 2001, '2026-08-22 12:00:00', -40.00, 'Demo Grocer A', 'groceries', 'card'),
    (900111, 1001, 2001, '2026-08-25 12:00:00', -53.33, 'Demo Shop A', 'shopping', 'card'),
    (900112, 1001, 2001, '2026-08-26 12:00:00', -40.00, 'Demo Grocer A', 'groceries', 'card'),
    (900113, 1001, 2001, '2026-08-26 12:00:00', -15.00, 'Demo Transit A', 'transport', 'card'),
    (900114, 1001, 2001, '2026-08-27 12:00:00', -50.00, 'Demo Cafe A', 'dining', 'card'),
    (900115, 1001, 2001, '2026-08-28 12:00:00', 2100.00, 'Demo Employer A', 'salary', 'bank_transfer'),
    (900116, 1001, 2001, '2026-08-29 12:00:00', -40.00, 'Demo Grocer A', 'groceries', 'card'),
    (900117, 1001, 2001, '2026-09-02 12:00:00', -41.25, 'Demo Grocer A', 'groceries', 'card'),
    (900118, 1001, 2001, '2026-09-03 12:00:00', -900.00, 'Demo Housing A', 'rent', 'direct_debit'),
    (900119, 1001, 2001, '2026-09-05 12:00:00', -15.00, 'Demo Transit A', 'transport', 'card'),
    (900120, 1001, 2001, '2026-09-06 12:00:00', -41.25, 'Demo Grocer A', 'groceries', 'card'),
    (900121, 1001, 2001, '2026-09-07 12:00:00', -80.00, 'Demo Cafe A', 'dining', 'card'),
    (900122, 1001, 2001, '2026-09-08 12:00:00', -93.34, 'Demo Shop A', 'shopping', 'card'),
    (900123, 1001, 2001, '2026-09-10 12:00:00', -41.25, 'Demo Grocer A', 'groceries', 'card'),
    (900124, 1001, 2001, '2026-09-12 12:00:00', -90.00, 'Demo Insurer A', 'insurance', 'direct_debit'),
    (900125, 1001, 2001, '2026-09-12 12:00:00', -15.00, 'Demo Transit A', 'transport', 'card'),
    (900126, 1001, 2001, '2026-09-14 12:00:00', -80.00, 'Demo Cafe A', 'dining', 'card'),
    (900127, 1001, 2001, '2026-09-14 12:00:00', -41.25, 'Demo Grocer A', 'groceries', 'card'),
    (900128, 1001, 2001, '2026-09-17 12:00:00', -93.33, 'Demo Shop A', 'shopping', 'card'),
    (900129, 1001, 2001, '2026-09-18 12:00:00', -100.00, 'Demo Energy A', 'utilities', 'direct_debit'),
    (900130, 1001, 2001, '2026-09-18 12:00:00', -41.25, 'Demo Grocer A', 'groceries', 'card'),
    (900131, 1001, 2001, '2026-09-19 12:00:00', -15.00, 'Demo Transit A', 'transport', 'card'),
    (900132, 1001, 2001, '2026-09-21 12:00:00', -80.00, 'Demo Cafe A', 'dining', 'card'),
    (900133, 1001, 2001, '2026-09-22 12:00:00', -41.25, 'Demo Grocer A', 'groceries', 'card'),
    (900134, 1001, 2001, '2026-09-25 12:00:00', -93.33, 'Demo Shop A', 'shopping', 'card'),
    (900135, 1001, 2001, '2026-09-26 12:00:00', -41.25, 'Demo Grocer A', 'groceries', 'card'),
    (900136, 1001, 2001, '2026-09-26 12:00:00', -15.00, 'Demo Transit A', 'transport', 'card'),
    (900137, 1001, 2001, '2026-09-27 12:00:00', -80.00, 'Demo Cafe A', 'dining', 'card'),
    (900138, 1001, 2001, '2026-09-28 12:00:00', 2100.00, 'Demo Employer A', 'salary', 'bank_transfer'),
    (900139, 1001, 2001, '2026-09-29 12:00:00', -41.25, 'Demo Grocer A', 'groceries', 'card'),
    (900140, 1002, 2002, '2026-04-02 12:00:00', -40.00, 'Demo Grocer B', 'groceries', 'card'),
    (900141, 1002, 2002, '2026-04-02 12:00:00', -850.00, 'Demo Housing B', 'rent', 'direct_debit'),
    (900142, 1002, 2002, '2026-04-05 12:00:00', -20.00, 'Demo Transit B', 'transport', 'card'),
    (900143, 1002, 2002, '2026-04-06 12:00:00', -40.00, 'Demo Grocer B', 'groceries', 'card'),
    (900144, 1002, 2002, '2026-04-07 12:00:00', -25.00, 'Demo Cafe B', 'dining', 'card'),
    (900145, 1002, 2002, '2026-04-08 12:00:00', -26.67, 'Demo Shop B', 'shopping', 'card'),
    (900146, 1002, 2002, '2026-04-10 12:00:00', -40.00, 'Demo Grocer B', 'groceries', 'card'),
    (900147, 1002, 2002, '2026-04-11 12:00:00', -80.00, 'Demo Insurer B', 'insurance', 'direct_debit'),
    (900148, 1002, 2002, '2026-04-12 12:00:00', -20.00, 'Demo Transit B', 'transport', 'card'),
    (900149, 1002, 2002, '2026-04-14 12:00:00', -25.00, 'Demo Cafe B', 'dining', 'card'),
    (900150, 1002, 2002, '2026-04-14 12:00:00', -40.00, 'Demo Grocer B', 'groceries', 'card'),
    (900151, 1002, 2002, '2026-04-17 12:00:00', -26.67, 'Demo Shop B', 'shopping', 'card'),
    (900152, 1002, 2002, '2026-04-18 12:00:00', -110.00, 'Demo Energy B', 'utilities', 'direct_debit'),
    (900153, 1002, 2002, '2026-04-18 12:00:00', -40.00, 'Demo Grocer B', 'groceries', 'card'),
    (900154, 1002, 2002, '2026-04-19 12:00:00', -20.00, 'Demo Transit B', 'transport', 'card'),
    (900155, 1002, 2002, '2026-04-21 12:00:00', -25.00, 'Demo Cafe B', 'dining', 'card'),
    (900156, 1002, 2002, '2026-04-22 12:00:00', -40.00, 'Demo Grocer B', 'groceries', 'card'),
    (900157, 1002, 2002, '2026-04-25 12:00:00', 2800.00, 'Demo Employer B', 'salary', 'bank_transfer'),
    (900158, 1002, 2002, '2026-04-25 12:00:00', -26.66, 'Demo Shop B', 'shopping', 'card'),
    (900159, 1002, 2002, '2026-04-26 12:00:00', -40.00, 'Demo Grocer B', 'groceries', 'card'),
    (900160, 1002, 2002, '2026-04-26 12:00:00', -20.00, 'Demo Transit B', 'transport', 'card'),
    (900161, 1002, 2002, '2026-04-27 12:00:00', -25.00, 'Demo Cafe B', 'dining', 'card'),
    (900162, 1002, 2002, '2026-04-29 12:00:00', -40.00, 'Demo Grocer B', 'groceries', 'card'),
    (900163, 1002, 2002, '2026-05-02 12:00:00', -41.88, 'Demo Grocer B', 'groceries', 'card'),
    (900164, 1002, 2002, '2026-05-02 12:00:00', -850.00, 'Demo Housing B', 'rent', 'direct_debit'),
    (900165, 1002, 2002, '2026-05-05 12:00:00', -20.00, 'Demo Transit B', 'transport', 'card'),
    (900166, 1002, 2002, '2026-05-06 12:00:00', -41.88, 'Demo Grocer B', 'groceries', 'card'),
    (900167, 1002, 2002, '2026-05-07 12:00:00', -27.50, 'Demo Cafe B', 'dining', 'card'),
    (900168, 1002, 2002, '2026-05-08 12:00:00', -33.34, 'Demo Shop B', 'shopping', 'card'),
    (900169, 1002, 2002, '2026-05-10 12:00:00', -41.88, 'Demo Grocer B', 'groceries', 'card'),
    (900170, 1002, 2002, '2026-05-11 12:00:00', -80.00, 'Demo Insurer B', 'insurance', 'direct_debit'),
    (900171, 1002, 2002, '2026-05-12 12:00:00', -20.00, 'Demo Transit B', 'transport', 'card'),
    (900172, 1002, 2002, '2026-05-14 12:00:00', -27.50, 'Demo Cafe B', 'dining', 'card'),
    (900173, 1002, 2002, '2026-05-14 12:00:00', -41.88, 'Demo Grocer B', 'groceries', 'card'),
    (900174, 1002, 2002, '2026-05-17 12:00:00', -33.33, 'Demo Shop B', 'shopping', 'card'),
    (900175, 1002, 2002, '2026-05-18 12:00:00', -110.00, 'Demo Energy B', 'utilities', 'direct_debit'),
    (900176, 1002, 2002, '2026-05-18 12:00:00', -41.87, 'Demo Grocer B', 'groceries', 'card'),
    (900177, 1002, 2002, '2026-05-19 12:00:00', -20.00, 'Demo Transit B', 'transport', 'card'),
    (900178, 1002, 2002, '2026-05-21 12:00:00', -27.50, 'Demo Cafe B', 'dining', 'card'),
    (900179, 1002, 2002, '2026-05-22 12:00:00', -41.87, 'Demo Grocer B', 'groceries', 'card'),
    (900180, 1002, 2002, '2026-05-25 12:00:00', 2800.00, 'Demo Employer B', 'salary', 'bank_transfer'),
    (900181, 1002, 2002, '2026-05-25 12:00:00', -33.33, 'Demo Shop B', 'shopping', 'card'),
    (900182, 1002, 2002, '2026-05-26 12:00:00', -41.87, 'Demo Grocer B', 'groceries', 'card'),
    (900183, 1002, 2002, '2026-05-26 12:00:00', -20.00, 'Demo Transit B', 'transport', 'card'),
    (900184, 1002, 2002, '2026-05-27 12:00:00', -27.50, 'Demo Cafe B', 'dining', 'card'),
    (900185, 1002, 2002, '2026-05-29 12:00:00', -41.87, 'Demo Grocer B', 'groceries', 'card'),
    (900186, 1002, 2002, '2026-06-02 12:00:00', -39.38, 'Demo Grocer B', 'groceries', 'card'),
    (900187, 1002, 2002, '2026-06-02 12:00:00', -850.00, 'Demo Housing B', 'rent', 'direct_debit'),
    (900188, 1002, 2002, '2026-06-05 12:00:00', -20.00, 'Demo Transit B', 'transport', 'card'),
    (900189, 1002, 2002, '2026-06-06 12:00:00', -39.38, 'Demo Grocer B', 'groceries', 'card'),
    (900190, 1002, 2002, '2026-06-07 12:00:00', -22.50, 'Demo Cafe B', 'dining', 'card'),
    (900191, 1002, 2002, '2026-06-08 12:00:00', -20.00, 'Demo Shop B', 'shopping', 'card'),
    (900192, 1002, 2002, '2026-06-10 12:00:00', -39.38, 'Demo Grocer B', 'groceries', 'card'),
    (900193, 1002, 2002, '2026-06-11 12:00:00', -80.00, 'Demo Insurer B', 'insurance', 'direct_debit'),
    (900194, 1002, 2002, '2026-06-12 12:00:00', -20.00, 'Demo Transit B', 'transport', 'card'),
    (900195, 1002, 2002, '2026-06-14 12:00:00', -22.50, 'Demo Cafe B', 'dining', 'card'),
    (900196, 1002, 2002, '2026-06-14 12:00:00', -39.38, 'Demo Grocer B', 'groceries', 'card'),
    (900197, 1002, 2002, '2026-06-17 12:00:00', -20.00, 'Demo Shop B', 'shopping', 'card'),
    (900198, 1002, 2002, '2026-06-18 12:00:00', -110.00, 'Demo Energy B', 'utilities', 'direct_debit'),
    (900199, 1002, 2002, '2026-06-18 12:00:00', -39.37, 'Demo Grocer B', 'groceries', 'card'),
    (900200, 1002, 2002, '2026-06-19 12:00:00', -20.00, 'Demo Transit B', 'transport', 'card'),
    (900201, 1002, 2002, '2026-06-21 12:00:00', -22.50, 'Demo Cafe B', 'dining', 'card'),
    (900202, 1002, 2002, '2026-06-22 12:00:00', -39.37, 'Demo Grocer B', 'groceries', 'card'),
    (900203, 1002, 2002, '2026-06-25 12:00:00', 2800.00, 'Demo Employer B', 'salary', 'bank_transfer'),
    (900204, 1002, 2002, '2026-06-25 12:00:00', -20.00, 'Demo Shop B', 'shopping', 'card'),
    (900205, 1002, 2002, '2026-06-26 12:00:00', -39.37, 'Demo Grocer B', 'groceries', 'card'),
    (900206, 1002, 2002, '2026-06-26 12:00:00', -20.00, 'Demo Transit B', 'transport', 'card'),
    (900207, 1002, 2002, '2026-06-27 12:00:00', -22.50, 'Demo Cafe B', 'dining', 'card'),
    (900208, 1002, 2002, '2026-06-29 12:00:00', -39.37, 'Demo Grocer B', 'groceries', 'card'),
    (900209, 1002, 2002, '2026-06-29 12:00:00', -5000.00, 'Own account savings', 'savings', 'internal_transfer'),
    (900210, 1002, 2002, '2026-07-02 12:00:00', -42.50, 'Demo Grocer B', 'groceries', 'card'),
    (900211, 1002, 2002, '2026-07-02 12:00:00', -850.00, 'Demo Housing B', 'rent', 'direct_debit'),
    (900212, 1002, 2002, '2026-07-05 12:00:00', -20.00, 'Demo Transit B', 'transport', 'card'),
    (900213, 1002, 2002, '2026-07-06 12:00:00', -42.50, 'Demo Grocer B', 'groceries', 'card'),
    (900214, 1002, 2002, '2026-07-07 12:00:00', -30.00, 'Demo Cafe B', 'dining', 'card'),
    (900215, 1002, 2002, '2026-07-08 12:00:00', -30.00, 'Demo Shop B', 'shopping', 'card'),
    (900216, 1002, 2002, '2026-07-10 12:00:00', -42.50, 'Demo Grocer B', 'groceries', 'card'),
    (900217, 1002, 2002, '2026-07-11 12:00:00', -80.00, 'Demo Insurer B', 'insurance', 'direct_debit'),
    (900218, 1002, 2002, '2026-07-12 12:00:00', -20.00, 'Demo Transit B', 'transport', 'card'),
    (900219, 1002, 2002, '2026-07-14 12:00:00', -30.00, 'Demo Cafe B', 'dining', 'card'),
    (900220, 1002, 2002, '2026-07-14 12:00:00', -42.50, 'Demo Grocer B', 'groceries', 'card'),
    (900221, 1002, 2002, '2026-07-17 12:00:00', -30.00, 'Demo Shop B', 'shopping', 'card'),
    (900222, 1002, 2002, '2026-07-18 12:00:00', -110.00, 'Demo Energy B', 'utilities', 'direct_debit'),
    (900223, 1002, 2002, '2026-07-18 12:00:00', -42.50, 'Demo Grocer B', 'groceries', 'card'),
    (900224, 1002, 2002, '2026-07-19 12:00:00', -20.00, 'Demo Transit B', 'transport', 'card'),
    (900225, 1002, 2002, '2026-07-21 12:00:00', -30.00, 'Demo Cafe B', 'dining', 'card'),
    (900226, 1002, 2002, '2026-07-22 12:00:00', -42.50, 'Demo Grocer B', 'groceries', 'card'),
    (900227, 1002, 2002, '2026-07-25 12:00:00', 2800.00, 'Demo Employer B', 'salary', 'bank_transfer'),
    (900228, 1002, 2002, '2026-07-25 12:00:00', -30.00, 'Demo Shop B', 'shopping', 'card'),
    (900229, 1002, 2002, '2026-07-26 12:00:00', -42.50, 'Demo Grocer B', 'groceries', 'card'),
    (900230, 1002, 2002, '2026-07-26 12:00:00', -20.00, 'Demo Transit B', 'transport', 'card'),
    (900231, 1002, 2002, '2026-07-27 12:00:00', -30.00, 'Demo Cafe B', 'dining', 'card'),
    (900232, 1002, 2002, '2026-07-29 12:00:00', -42.50, 'Demo Grocer B', 'groceries', 'card'),
    (900233, 1002, 2002, '2026-08-02 12:00:00', -41.25, 'Demo Grocer B', 'groceries', 'card'),
    (900234, 1002, 2002, '2026-08-02 12:00:00', -850.00, 'Demo Housing B', 'rent', 'direct_debit'),
    (900235, 1002, 2002, '2026-08-05 12:00:00', -20.00, 'Demo Transit B', 'transport', 'card'),
    (900236, 1002, 2002, '2026-08-06 12:00:00', -41.25, 'Demo Grocer B', 'groceries', 'card'),
    (900237, 1002, 2002, '2026-08-07 12:00:00', -25.00, 'Demo Cafe B', 'dining', 'card'),
    (900238, 1002, 2002, '2026-08-08 12:00:00', -23.34, 'Demo Shop B', 'shopping', 'card'),
    (900239, 1002, 2002, '2026-08-10 12:00:00', -41.25, 'Demo Grocer B', 'groceries', 'card'),
    (900240, 1002, 2002, '2026-08-11 12:00:00', -80.00, 'Demo Insurer B', 'insurance', 'direct_debit'),
    (900241, 1002, 2002, '2026-08-12 12:00:00', -20.00, 'Demo Transit B', 'transport', 'card'),
    (900242, 1002, 2002, '2026-08-14 12:00:00', -25.00, 'Demo Cafe B', 'dining', 'card'),
    (900243, 1002, 2002, '2026-08-14 12:00:00', -41.25, 'Demo Grocer B', 'groceries', 'card'),
    (900244, 1002, 2002, '2026-08-17 12:00:00', -23.33, 'Demo Shop B', 'shopping', 'card'),
    (900245, 1002, 2002, '2026-08-18 12:00:00', -110.00, 'Demo Energy B', 'utilities', 'direct_debit'),
    (900246, 1002, 2002, '2026-08-18 12:00:00', -41.25, 'Demo Grocer B', 'groceries', 'card'),
    (900247, 1002, 2002, '2026-08-19 12:00:00', -20.00, 'Demo Transit B', 'transport', 'card'),
    (900248, 1002, 2002, '2026-08-21 12:00:00', -25.00, 'Demo Cafe B', 'dining', 'card'),
    (900249, 1002, 2002, '2026-08-22 12:00:00', -41.25, 'Demo Grocer B', 'groceries', 'card'),
    (900250, 1002, 2002, '2026-08-25 12:00:00', 2800.00, 'Demo Employer B', 'salary', 'bank_transfer'),
    (900251, 1002, 2002, '2026-08-25 12:00:00', -23.33, 'Demo Shop B', 'shopping', 'card'),
    (900252, 1002, 2002, '2026-08-26 12:00:00', -41.25, 'Demo Grocer B', 'groceries', 'card'),
    (900253, 1002, 2002, '2026-08-26 12:00:00', -20.00, 'Demo Transit B', 'transport', 'card'),
    (900254, 1002, 2002, '2026-08-27 12:00:00', -25.00, 'Demo Cafe B', 'dining', 'card'),
    (900255, 1002, 2002, '2026-08-29 12:00:00', -41.25, 'Demo Grocer B', 'groceries', 'card'),
    (900256, 1002, 2002, '2026-09-02 12:00:00', -43.75, 'Demo Grocer B', 'groceries', 'card'),
    (900257, 1002, 2002, '2026-09-02 12:00:00', -850.00, 'Demo Housing B', 'rent', 'direct_debit'),
    (900258, 1002, 2002, '2026-09-05 12:00:00', -20.00, 'Demo Transit B', 'transport', 'card'),
    (900259, 1002, 2002, '2026-09-06 12:00:00', -43.75, 'Demo Grocer B', 'groceries', 'card'),
    (900260, 1002, 2002, '2026-09-07 12:00:00', -27.50, 'Demo Cafe B', 'dining', 'card'),
    (900261, 1002, 2002, '2026-09-08 12:00:00', -28.34, 'Demo Shop B', 'shopping', 'card'),
    (900262, 1002, 2002, '2026-09-10 12:00:00', -43.75, 'Demo Grocer B', 'groceries', 'card'),
    (900263, 1002, 2002, '2026-09-11 12:00:00', -80.00, 'Demo Insurer B', 'insurance', 'direct_debit'),
    (900264, 1002, 2002, '2026-09-12 12:00:00', -20.00, 'Demo Transit B', 'transport', 'card'),
    (900265, 1002, 2002, '2026-09-14 12:00:00', -27.50, 'Demo Cafe B', 'dining', 'card'),
    (900266, 1002, 2002, '2026-09-14 12:00:00', -43.75, 'Demo Grocer B', 'groceries', 'card'),
    (900267, 1002, 2002, '2026-09-17 12:00:00', -28.33, 'Demo Shop B', 'shopping', 'card'),
    (900268, 1002, 2002, '2026-09-18 12:00:00', -110.00, 'Demo Energy B', 'utilities', 'direct_debit'),
    (900269, 1002, 2002, '2026-09-18 12:00:00', -43.75, 'Demo Grocer B', 'groceries', 'card'),
    (900270, 1002, 2002, '2026-09-19 12:00:00', -20.00, 'Demo Transit B', 'transport', 'card'),
    (900271, 1002, 2002, '2026-09-21 12:00:00', -27.50, 'Demo Cafe B', 'dining', 'card'),
    (900272, 1002, 2002, '2026-09-22 12:00:00', -43.75, 'Demo Grocer B', 'groceries', 'card'),
    (900273, 1002, 2002, '2026-09-25 12:00:00', 2800.00, 'Demo Employer B', 'salary', 'bank_transfer'),
    (900274, 1002, 2002, '2026-09-25 12:00:00', -28.33, 'Demo Shop B', 'shopping', 'card'),
    (900275, 1002, 2002, '2026-09-26 12:00:00', -43.75, 'Demo Grocer B', 'groceries', 'card'),
    (900276, 1002, 2002, '2026-09-26 12:00:00', -20.00, 'Demo Transit B', 'transport', 'card'),
    (900277, 1002, 2002, '2026-09-27 12:00:00', -27.50, 'Demo Cafe B', 'dining', 'card'),
    (900278, 1002, 2002, '2026-09-29 12:00:00', -43.75, 'Demo Grocer B', 'groceries', 'card'),
    (900279, 1003, 2003, '2026-04-02 12:00:00', -28.75, 'Demo Grocer C', 'groceries', 'card'),
    (900280, 1003, 2003, '2026-04-04 12:00:00', -620.00, 'Demo Housing C', 'rent', 'bank_transfer'),
    (900281, 1003, 2003, '2026-04-05 12:00:00', -11.25, 'Demo Transit C', 'transport', 'card'),
    (900282, 1003, 2003, '2026-04-06 12:00:00', -28.75, 'Demo Grocer C', 'groceries', 'card'),
    (900283, 1003, 2003, '2026-04-07 12:00:00', -15.00, 'Demo Cafe C', 'dining', 'card'),
    (900284, 1003, 2003, '2026-04-08 12:00:00', 1500.00, 'Demo Freelance Client A', 'freelance_income', 'bank_transfer'),
    (900285, 1003, 2003, '2026-04-10 12:00:00', -28.75, 'Demo Grocer C', 'groceries', 'card'),
    (900286, 1003, 2003, '2026-04-12 12:00:00', -11.25, 'Demo Transit C', 'transport', 'card'),
    (900287, 1003, 2003, '2026-04-14 12:00:00', -15.00, 'Demo Cafe C', 'dining', 'card'),
    (900288, 1003, 2003, '2026-04-14 12:00:00', -28.75, 'Demo Grocer C', 'groceries', 'card'),
    (900289, 1003, 2003, '2026-04-18 12:00:00', -28.75, 'Demo Grocer C', 'groceries', 'card'),
    (900290, 1003, 2003, '2026-04-19 12:00:00', -11.25, 'Demo Transit C', 'transport', 'card'),
    (900291, 1003, 2003, '2026-04-21 12:00:00', -15.00, 'Demo Cafe C', 'dining', 'card'),
    (900292, 1003, 2003, '2026-04-22 12:00:00', -28.75, 'Demo Grocer C', 'groceries', 'card'),
    (900293, 1003, 2003, '2026-04-24 12:00:00', 350.00, 'Demo Freelance Client B', 'freelance_income', 'bank_transfer'),
    (900294, 1003, 2003, '2026-04-26 12:00:00', -28.75, 'Demo Grocer C', 'groceries', 'card'),
    (900295, 1003, 2003, '2026-04-26 12:00:00', -11.25, 'Demo Transit C', 'transport', 'card'),
    (900296, 1003, 2003, '2026-04-27 12:00:00', -15.00, 'Demo Cafe C', 'dining', 'card'),
    (900297, 1003, 2003, '2026-04-29 12:00:00', -28.75, 'Demo Grocer C', 'groceries', 'card'),
    (900298, 1003, 2003, '2026-05-02 12:00:00', -31.88, 'Demo Grocer C', 'groceries', 'card'),
    (900299, 1003, 2003, '2026-05-04 12:00:00', -620.00, 'Demo Housing C', 'rent', 'bank_transfer'),
    (900300, 1003, 2003, '2026-05-05 12:00:00', -11.25, 'Demo Transit C', 'transport', 'card'),
    (900301, 1003, 2003, '2026-05-06 12:00:00', -31.88, 'Demo Grocer C', 'groceries', 'card'),
    (900302, 1003, 2003, '2026-05-07 12:00:00', -30.00, 'Demo Cafe C', 'dining', 'card'),
    (900303, 1003, 2003, '2026-05-10 12:00:00', -31.88, 'Demo Grocer C', 'groceries', 'card'),
    (900304, 1003, 2003, '2026-05-12 12:00:00', -11.25, 'Demo Transit C', 'transport', 'card'),
    (900305, 1003, 2003, '2026-05-14 12:00:00', -30.00, 'Demo Cafe C', 'dining', 'card'),
    (900306, 1003, 2003, '2026-05-14 12:00:00', -31.88, 'Demo Grocer C', 'groceries', 'card'),
    (900307, 1003, 2003, '2026-05-16 12:00:00', 780.00, 'Demo Freelance Client C', 'freelance_income', 'bank_transfer'),
    (900308, 1003, 2003, '2026-05-18 12:00:00', -31.87, 'Demo Grocer C', 'groceries', 'card'),
    (900309, 1003, 2003, '2026-05-19 12:00:00', -11.25, 'Demo Transit C', 'transport', 'card'),
    (900310, 1003, 2003, '2026-05-21 12:00:00', -30.00, 'Demo Cafe C', 'dining', 'card'),
    (900311, 1003, 2003, '2026-05-22 12:00:00', -31.87, 'Demo Grocer C', 'groceries', 'card'),
    (900312, 1003, 2003, '2026-05-26 12:00:00', -31.87, 'Demo Grocer C', 'groceries', 'card'),
    (900313, 1003, 2003, '2026-05-26 12:00:00', -11.25, 'Demo Transit C', 'transport', 'card'),
    (900314, 1003, 2003, '2026-05-27 12:00:00', -30.00, 'Demo Cafe C', 'dining', 'card'),
    (900315, 1003, 2003, '2026-05-29 12:00:00', -31.87, 'Demo Grocer C', 'groceries', 'card'),
    (900316, 1003, 2003, '2026-06-02 12:00:00', -30.63, 'Demo Grocer C', 'groceries', 'card'),
    (900317, 1003, 2003, '2026-06-04 12:00:00', -620.00, 'Demo Housing C', 'rent', 'bank_transfer'),
    (900318, 1003, 2003, '2026-06-05 12:00:00', 1200.00, 'Demo Freelance Client A', 'freelance_income', 'bank_transfer'),
    (900319, 1003, 2003, '2026-06-05 12:00:00', -11.25, 'Demo Transit C', 'transport', 'card'),
    (900320, 1003, 2003, '2026-06-06 12:00:00', -30.63, 'Demo Grocer C', 'groceries', 'card'),
    (900321, 1003, 2003, '2026-06-07 12:00:00', -10.00, 'Demo Cafe C', 'dining', 'card'),
    (900322, 1003, 2003, '2026-06-10 12:00:00', -30.63, 'Demo Grocer C', 'groceries', 'card'),
    (900323, 1003, 2003, '2026-06-12 12:00:00', -11.25, 'Demo Transit C', 'transport', 'card'),
    (900324, 1003, 2003, '2026-06-14 12:00:00', -10.00, 'Demo Cafe C', 'dining', 'card'),
    (900325, 1003, 2003, '2026-06-14 12:00:00', -30.63, 'Demo Grocer C', 'groceries', 'card'),
    (900326, 1003, 2003, '2026-06-18 12:00:00', -30.62, 'Demo Grocer C', 'groceries', 'card'),
    (900327, 1003, 2003, '2026-06-19 12:00:00', -11.25, 'Demo Transit C', 'transport', 'card'),
    (900328, 1003, 2003, '2026-06-21 12:00:00', -10.00, 'Demo Cafe C', 'dining', 'card'),
    (900329, 1003, 2003, '2026-06-22 12:00:00', -30.62, 'Demo Grocer C', 'groceries', 'card'),
    (900330, 1003, 2003, '2026-06-26 12:00:00', -30.62, 'Demo Grocer C', 'groceries', 'card'),
    (900331, 1003, 2003, '2026-06-26 12:00:00', -11.25, 'Demo Transit C', 'transport', 'card'),
    (900332, 1003, 2003, '2026-06-27 12:00:00', -10.00, 'Demo Cafe C', 'dining', 'card'),
    (900333, 1003, 2003, '2026-06-27 12:00:00', 400.00, 'Demo Freelance Client D', 'freelance_income', 'bank_transfer'),
    (900334, 1003, 2003, '2026-06-29 12:00:00', -30.62, 'Demo Grocer C', 'groceries', 'card'),
    (900335, 1003, 2003, '2026-07-02 12:00:00', -32.50, 'Demo Grocer C', 'groceries', 'card'),
    (900336, 1003, 2003, '2026-07-04 12:00:00', -620.00, 'Demo Housing C', 'rent', 'bank_transfer'),
    (900337, 1003, 2003, '2026-07-05 12:00:00', -11.25, 'Demo Transit C', 'transport', 'card'),
    (900338, 1003, 2003, '2026-07-06 12:00:00', -32.50, 'Demo Grocer C', 'groceries', 'card'),
    (900339, 1003, 2003, '2026-07-07 12:00:00', -22.50, 'Demo Cafe C', 'dining', 'card'),
    (900340, 1003, 2003, '2026-07-09 12:00:00', 1050.00, 'Demo Freelance Client B', 'freelance_income', 'bank_transfer'),
    (900341, 1003, 2003, '2026-07-10 12:00:00', -32.50, 'Demo Grocer C', 'groceries', 'card'),
    (900342, 1003, 2003, '2026-07-12 12:00:00', -11.25, 'Demo Transit C', 'transport', 'card'),
    (900343, 1003, 2003, '2026-07-14 12:00:00', -22.50, 'Demo Cafe C', 'dining', 'card'),
    (900344, 1003, 2003, '2026-07-14 12:00:00', -32.50, 'Demo Grocer C', 'groceries', 'card'),
    (900345, 1003, 2003, '2026-07-18 12:00:00', -32.50, 'Demo Grocer C', 'groceries', 'card'),
    (900346, 1003, 2003, '2026-07-19 12:00:00', -11.25, 'Demo Transit C', 'transport', 'card'),
    (900347, 1003, 2003, '2026-07-21 12:00:00', -22.50, 'Demo Cafe C', 'dining', 'card'),
    (900348, 1003, 2003, '2026-07-22 12:00:00', -32.50, 'Demo Grocer C', 'groceries', 'card'),
    (900349, 1003, 2003, '2026-07-26 12:00:00', -32.50, 'Demo Grocer C', 'groceries', 'card'),
    (900350, 1003, 2003, '2026-07-26 12:00:00', -11.25, 'Demo Transit C', 'transport', 'card'),
    (900351, 1003, 2003, '2026-07-27 12:00:00', -22.50, 'Demo Cafe C', 'dining', 'card'),
    (900352, 1003, 2003, '2026-07-29 12:00:00', -32.50, 'Demo Grocer C', 'groceries', 'card'),
    (900353, 1003, 2003, '2026-08-02 12:00:00', -30.00, 'Demo Grocer C', 'groceries', 'card'),
    (900354, 1003, 2003, '2026-08-04 12:00:00', -620.00, 'Demo Housing C', 'rent', 'bank_transfer'),
    (900355, 1003, 2003, '2026-08-05 12:00:00', -11.25, 'Demo Transit C', 'transport', 'card'),
    (900356, 1003, 2003, '2026-08-06 12:00:00', -30.00, 'Demo Grocer C', 'groceries', 'card'),
    (900357, 1003, 2003, '2026-08-07 12:00:00', -12.50, 'Demo Cafe C', 'dining', 'card'),
    (900358, 1003, 2003, '2026-08-10 12:00:00', -30.00, 'Demo Grocer C', 'groceries', 'card'),
    (900359, 1003, 2003, '2026-08-12 12:00:00', -11.25, 'Demo Transit C', 'transport', 'card'),
    (900360, 1003, 2003, '2026-08-14 12:00:00', -12.50, 'Demo Cafe C', 'dining', 'card'),
    (900361, 1003, 2003, '2026-08-14 12:00:00', -30.00, 'Demo Grocer C', 'groceries', 'card'),
    (900362, 1003, 2003, '2026-08-18 12:00:00', -30.00, 'Demo Grocer C', 'groceries', 'card'),
    (900363, 1003, 2003, '2026-08-19 12:00:00', 720.00, 'Demo Freelance Client A', 'freelance_income', 'bank_transfer'),
    (900364, 1003, 2003, '2026-08-19 12:00:00', -11.25, 'Demo Transit C', 'transport', 'card'),
    (900365, 1003, 2003, '2026-08-21 12:00:00', -12.50, 'Demo Cafe C', 'dining', 'card'),
    (900366, 1003, 2003, '2026-08-22 12:00:00', -30.00, 'Demo Grocer C', 'groceries', 'card'),
    (900367, 1003, 2003, '2026-08-26 12:00:00', -30.00, 'Demo Grocer C', 'groceries', 'card'),
    (900368, 1003, 2003, '2026-08-26 12:00:00', -11.25, 'Demo Transit C', 'transport', 'card'),
    (900369, 1003, 2003, '2026-08-27 12:00:00', -12.50, 'Demo Cafe C', 'dining', 'card'),
    (900370, 1003, 2003, '2026-08-29 12:00:00', -30.00, 'Demo Grocer C', 'groceries', 'card'),
    (900371, 1003, 2003, '2026-09-02 12:00:00', -33.75, 'Demo Grocer C', 'groceries', 'card'),
    (900372, 1003, 2003, '2026-09-04 12:00:00', -620.00, 'Demo Housing C', 'rent', 'bank_transfer'),
    (900373, 1003, 2003, '2026-09-05 12:00:00', -11.25, 'Demo Transit C', 'transport', 'card'),
    (900374, 1003, 2003, '2026-09-06 12:00:00', 350.00, 'Demo Freelance Client C', 'freelance_income', 'bank_transfer'),
    (900375, 1003, 2003, '2026-09-06 12:00:00', -33.75, 'Demo Grocer C', 'groceries', 'card'),
    (900376, 1003, 2003, '2026-09-07 12:00:00', -27.50, 'Demo Cafe C', 'dining', 'card'),
    (900377, 1003, 2003, '2026-09-10 12:00:00', -33.75, 'Demo Grocer C', 'groceries', 'card'),
    (900378, 1003, 2003, '2026-09-12 12:00:00', -11.25, 'Demo Transit C', 'transport', 'card'),
    (900379, 1003, 2003, '2026-09-14 12:00:00', -27.50, 'Demo Cafe C', 'dining', 'card'),
    (900380, 1003, 2003, '2026-09-14 12:00:00', -33.75, 'Demo Grocer C', 'groceries', 'card'),
    (900381, 1003, 2003, '2026-09-18 12:00:00', -33.75, 'Demo Grocer C', 'groceries', 'card'),
    (900382, 1003, 2003, '2026-09-19 12:00:00', -11.25, 'Demo Transit C', 'transport', 'card'),
    (900383, 1003, 2003, '2026-09-21 12:00:00', -27.50, 'Demo Cafe C', 'dining', 'card'),
    (900384, 1003, 2003, '2026-09-22 12:00:00', -33.75, 'Demo Grocer C', 'groceries', 'card'),
    (900385, 1003, 2003, '2026-09-23 12:00:00', 280.00, 'Demo Freelance Client D', 'freelance_income', 'bank_transfer'),
    (900386, 1003, 2003, '2026-09-26 12:00:00', -33.75, 'Demo Grocer C', 'groceries', 'card'),
    (900387, 1003, 2003, '2026-09-26 12:00:00', -11.25, 'Demo Transit C', 'transport', 'card'),
    (900388, 1003, 2003, '2026-09-27 12:00:00', -27.50, 'Demo Cafe C', 'dining', 'card'),
    (900389, 1003, 2003, '2026-09-29 12:00:00', -33.75, 'Demo Grocer C', 'groceries', 'card');

INSERT INTO events (event_id, event_type, event_date, event_value) VALUES
    (8001, 'demo_opening_balance', '2026-04-01 00:00:00', '1356.00'),
    (8002, 'demo_opening_balance', '2026-04-01 00:00:00', '2525.00'),
    (8003, 'demo_opening_balance', '2026-04-01 00:00:00', '230.00');

INSERT INTO customer_events (event_id, customer_id) VALUES
    (8001, 1001),
    (8002, 1002),
    (8003, 1003);

COMMIT;
